# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: master-vol
    vol_size: 100
  - vol_name: worker1-vol
    vol_size: 50
  - vol_name: worker2-vol
    vol_size: 50
  - vol_name: worker3-vol
    vol_size: 50


#Mount points
mountpoint:
  - default: /dev/vdb
    new_mount: /cnc2

# Security group
security_groups:
  - name: CnC_ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: CnC_http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: CnC_Couchdb
    description: "Port open for accessing couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: CnC_Server_Nodes
    description: "Port open for K8s node"
    protocol: tcp
    port_range_min: 30000
    port_range_max: 30000
    remote_ip_prefix: 0.0.0.0/0
  
  - name: CnC_Load_Balancer
    description: "Port open for K8s node"
    protocol: tcp
    port_range_min: 30001
    port_range_max: 30001
    remote_ip_prefix: 0.0.0.0/0
    

  - name: CnC_Cluster
    description: "Default Port open for node server"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: Master
    volumes: master-vol
  - name: Worker_1
    volumes: worker1-vol
  - name: Worker_2
    volumes: worker2-vol
  - name: Worker_3
    volumes: worker3-vol

instance_image: 3030ae9f-cf87-4eeb-8aee-eaec6a01da11
instance_key_name: CnC_Key_Pair
instance_flavor: uom.mse.2c9g

#kubernetes_join_comand: ""
