--- 
## Team number: 15
## City: Melbourne 
## Team Members: Aayush Mehta (1105081); Abhijeet Singh (1094984); Anoushka Doctor (1012827); Muhammad Atif (924009); Siddharth Agarwal (1077275)
docker_dir: /etc/systemd/system/docker.service.d
service_dir: /etc/systemd/system/docker.service.d/http-proxy.conf