---
## Team number: 15
## City: Melbourne 
## Team Members: Aayush Mehta (1105081); Abhijeet Singh (1094984); Anoushka Doctor (1012827); Muhammad Atif (924009); Siddharth Agarwal (1077275)

- name: install apt update and upgrade
  become: yes
  retries: 5
  delay: 4
  apt:
    upgrade: dist


- name: Fix all packages to the latest version
  become: yes
  apt:
    name: "*"
    state: fixed


# - name: Install dependencies
#   become: yes
#   apt:
#     name: ['pkg-config','erlang','build-essential','libicu-dev','libcurl4-openssl-dev','apt-transport-https', 'build-essential', 'ca-certificates', 'curl','python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
#     state: latest
#     install_recommends: no 
#     update_cache: yes



# - name: install apt update and upgrade
#   become: yes
#   apt:
#     upgrade: dist

- name: curl command
  become: yes
  apt_key:
    url: https://couchdb.apache.org/repo/bintray-pubkey.asc
    state: present

- name: echo command
  become: yes
  shell: echo "deb https://apache.bintray.com/couchdb-deb bionic main" | sudo tee -a /etc/apt/sources.list

- name: install apt update and upgrade
  become: yes
  apt:
    upgrade: dist

- name: install couchdb
  become: yes
  retries: 5
  delay: 4
  apt:
    name: couchdb
    state: latest
    update_cache: yes

- name: create the database directory
  become: yes
  file:
    state: directory
    path: '{{ database_dir }}'
    mode: '777'
          
- name: change ownership of the Database directory
  become: yes
  file:
    path: '{{ database_dir }}'
    owner: root
    group: root
    mode: '777'



- name: configure cluster
  become: yes
  replace:
    dest: '{{ vm_args }}'
    regexp: "^-name couchdb@127.0.0.1$"
    replace: "#INPUT"


- name: enter the config data
  become: yes
  blockinfile:
    dest: '{{ vm_args }}'
    insertafter: "^#INPUT$"
    block: |
      -name couchdb@{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}
      -kernel inet_dist_listen_min {{ inet_port }}
      -kernel inet_dist_listen_max {{ inet_port }}




- name: Register Admin Account
  become: yes 
  lineinfile:
      dest: '{{ local }}'
      insertafter: '^\[admins\]$'
      line: 'admin = qweasdzxc'

- name: wait command
  become: yes 
  wait_for:
    timeout: 10 



- name: start services
  become: yes
  retries: 5
  delay: 4
  systemd:
    state: started
    name: couchdb
  
- name: wait command
  become: yes 
  wait_for:
    timeout: 10  


- name: init command for all nodes
  become: yes
  shell: " curl -X POST -H \"Content-Type: application/json\" \
          http://admin:qweasdzxc@127.0.0.1:5984/_cluster_setup -d \
          '{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\", \
          \"username\": \"admin\", \"password\":\"qweasdzxc\", \"node_count\":\"{{ nodes }}\"}' "



