## Team number: 15
## City: Melbourne 
## Team Members: Aayush Mehta (1105081); Abhijeet Singh (1094984); Anoushka Doctor (1012827); Muhammad Atif (924009); Siddharth Agarwal (1077275)


FROM node:7
WORKDIR /app
COPY . /app
WORKDIR /app/ApplicationServer
RUN npm config set https-proxy http://wwwproxy.unimelb.edu.au:8000/
RUN npm config set proxy http://wwwproxy.unimelb.edu.au:8000/
RUN npm install
CMD node app.js
EXPOSE 3000