FROM node:7
WORKDIR /app
COPY . /app
WORKDIR /app/ApplicationServer
RUN npm config set https-proxy http://wwwproxy.unimelb.edu.au:8000/
RUN npm config set proxy http://wwwproxy.unimelb.edu.au:8000/
RUN npm install
CMD node loadbalancer.js
EXPOSE 3000