---
- hosts: webservers
  become: yes
  vars_files: 
    - Variables/main.yaml
  tasks:
  - name: echo msg
    command: echo Hello world


  # - name: install dependencies
  #   become: yes
  #   apt:
  #     name: ['pkg-config','erlang','build-essential','libicu-dev','libmozjs185-dev','libcurl4-openssl-dev','apt-transport-https','gnupg','ca-certificates']
  #     state: latest
  #     install_recommends: no
  #     update_cache: yes

  # - name: install deb package
  #   shell: echo "deb https://apache.bintray.com/couchdb-deb xenial main" | sudo tee -a /etc/apt/sources.list.d/couchdb.list


  # - name: Add an apt key by id from a keyserver
  #   apt_key:
  #     keyserver: keyserver.ubuntu.com
  #     id: 8756C4F765C9AC3CB6B85D62379CE192D401AB61


  # - name: Run the equivalent of "apt-get update" as a separate step
  #   become: yes
  #   apt:
  #     update_cache: yes


  # - name: install couchdb
  #   apt:
  #     name: couchdb
  #     state: latest


  # - name: Add CouchDB System Account
  #   user:
  #     name: couchdb
  #     comment: "CouchDB System Account"
  #     shell: /bin/bash
  #     system: yes
  #     home: /opt/couchdb
  #     createhome: no

  # - name: Change CouchDB Ownership
  #   file:
  #     path: /opt/couchdb
  #     owner: couchdb
  #     group: couchdb
  #     mode: 0770
  #     recurse: yes
  #     state: directory

  # - name: Change CouchDB Config File Permission
  #   file:
  #     path: /opt/couchdb/etc
  #     owner: couchdb
  #     group: couchdb
  #     mode: 0644
  #     recurse: yes
  #     state: directory

  # - name: Change CouchDB Directory Permission
  #   command: find /opt/couchdb -type d -exec chmod 0770 {} \;

  # - name: Change Node Name
  #   replace:
  #     dest: /opt/couchdb/etc/vm.args
  #     regexp: '^-name couchdb@127.0.0.1$'
  #     replace: '-name couchdb@115.146.93.160'

  # - name: Set Cookie
  #   replace:
  #     dest: /opt/couchdb/etc/vm.args
  #     regexp: '^-setcookie monster$'
  #     replace: '-setcookie siddharth'

  # - name: Bind Cluster Address to Public
  #   lineinfile:
  #     dest: /opt/couchdb/etc/local.ini
  #     insertafter: '^\[chttpd\]$'
  #     line: 'bind_address = 0.0.0.0'

  # - name: Bind Node Address to Public
  #   lineinfile:
  #     dest: /opt/couchdb/etc/local.ini
  #     insertafter: '^\[httpd\]$'
  #     line: 'bind_address = 0.0.0.0'

  # - name: change port
  #   become: yes
  #   replace:
  #     dest: /opt/couchdb/etc/local.d/10-admins.ini
  #     regexp: '^port = 80$'
  #     replace: 'port = 8083'


  ##### second part of autmation

  - name: Install dependencies
    become: yes
    apt:
      name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
      state: latest
      install_recommends: no
      update_cache: yes

  - name: install apt update and upgrade
    become: yes
    apt:
      upgrade: dist

  - name: Upgrade
    become: yes
    apt:
      name: "*"
      state: latest

  - name: curl command
    become: yes
    shell: curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | sudo apt-key add -

  - name: echo command
    become: yes
    shell: echo "deb https://apache.bintray.com/couchdb-deb bionic main" | sudo tee -a /etc/apt/sources.list

  - name: install apt update and upgrade
    become: yes
    apt:
      upgrade: dist
  
  - name: install couchdb
    become: yes
    apt:
      name: couchdb
      state: latest
      update_cache: yes
  - name: start services
    become: yes
    systemd:
      state: started
      name: couchdb

  - name: Bind Cluster Address to Public
    become: yes
    lineinfile:
      dest: /opt/couchdb/etc/local.ini
      insertafter: '^\[chttpd\]$'
      line: 'bind_address = 0.0.0.0'

  - name: Bind Cluster Address to Public
    become: yes 
    lineinfile:
        dest: /opt/couchdb/etc/local.ini
        insertafter: '^\[admins\]$'
        line: 'admin = qweasdzxc'

  - name: restart the service
    become: yes
    systemd:
      state: restarted
      daemon_reload: yes
      name: couchdb
